#! /bin/sh

sxhkd &
picom &
# kill all redshift processess to avoid flickering
#plasmashell &
feh --bg-scale ~/Pictures/wallpaperflare.com_wallpaper.jpg & 

bspc monitor -d I II III IV V VI VII VIII  IX X

bspc config border_width         5
bspc config window_gap           10

bspc config split_ratio          0.53
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config bottom_padding 60
bspc config focused_border_color "#fab387"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a dolphin state=floating
bspc rule -a spectacle state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
