#!/bin/sh

pkill -x sxhkd &
sxhkd &
picom &
setxkbmap -option caps:escape &

bspc monitor -d I II III IV V VI VII VIII  IX X

bspc config border_width         5
bspc config window_gap           10

bspc config split_ratio          0.53
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config top_padding 0
bspc config bottom_padding 60
bspc config focused_border_color "#fab387"

bspc config ignore_ewmh_focus true
bspc rule -a dolphin state=floating
bspc rule -a spectacle state=floating 
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a discord desktop='^3' follow=off focus=off
bspc rule -a Steam desktop='^4' follow=off focus=off state=tiled
